version: "3.7"

services:
  php-fs:
    container_name: php-fs
    build:
      dockerfile: ./.docker/Dockerfile
      context: .
      args:
        USER_ID: $USER_ID
    env_file: .env
    volumes:
      - .:/var/www/html/:delegated
